.grit/patterns/ReactToHooks.md

A pattern must have at least one big heading.

Fix ReactToHooks.md

---

.grit/patterns/FlowToTypeScript.md

Fixes #16 by attempting to insert `@import` comments as imports in the code.

fix: auto-import libs

---

.grit/patterns/ProtractorToPlaywright.md

Tested with `grit patterns test --pattern=ProtractorToPlaywright`

feat: Add ProtractorToPlaywright.md

---

.grit/patterns/AddTypeScriptTypes.md

Add a basic pattern for injecting type annotations where they're not currently found.

feat: add TypeScript pattern

---

.grit/patterns/common.grit

replace `exists` with `let`
tested in the pattern studio

remove exists

---

.grit/patterns/common.grit

replaces `outside` with `until` and `within`
tested relevant patterns and predicates in pattern studio

remove outside

---

.grit/patterns/ES6Imports.md

Resolves https://github.com/getgrit/rewriter/issues/3179 for now

JS2TS: ES6Imports change star behavior, and now handle more cases

---

.grit/patterns/AddTypeToCaughtErrors.md

Resolves https://github.com/getgrit/rewriter/issues/3692

feat: AddTypeToCaughtErrors

---

.grit/patterns/StrictTsConfig.md

https://app.grit.io/studio?key=tVoRolfpFrw4L2t-XEB1s

add StrictTsConfig

---

.grit/patterns/StyledJSXToCSSModules.md

**Iteration One:**
A initial working implementation of Styled JSX to CSS Modules.

feat: Styled JSX to CSS Modules pattern

---

.grit/patterns/StyledJSXToCSSModules.md

fix: styled jsx to css test

---

.grit/patterns/ES6Imports.md
.prettierrc

Fix the Es6Imports pattern to match engine formatting.

fix: add formatting config

---

.grit/patterns/ProtractorToPlaywright.md

1. Avoid inserting unnecessary `await` expressions.
2. Check presence, not count.

fix: various improvements to the Protractor pattern

---

.grit/patterns/NoConsoleLog.md
.grit/patterns/StyledJSXToCSSModules.md
.grit/patterns/common.grit
.grit/patterns/split_trpc_router.md
wip/RemoveUnusedImports.md

When your router gets big, split it up!

feat: add split_trpc_router

---

.grit/patterns/common.grit
.grit/patterns/split_trpc_router.md
wip/RemoveUnusedImports.md

Make the trpc case actually handle filtering.

fix: Improve imports

---

.grit/patterns/common.grit
.grit/patterns/split_trpc_router.md

feat: extract dirname predicate

---

.grit/patterns/ES6Exports.md
.grit/patterns/EnzymeToRTL.md
.grit/patterns/FixJSXFiles.md
.grit/patterns/JestArrayContaining.md
.grit/patterns/KnockoutToReact.md
.grit/patterns/NoIterator.md
.grit/patterns/ReactToHooks.md
.grit/patterns/StyledJSXToCSSModules.md

Note: Updates to patterns from the recast upgrade: https://github.com/getgrit/rewriter/pull/4350
**They need to be merged at the same time**

adapt to recast upgrade

---

.grit/patterns/PreferSelfClosingTagJSX.md
.grit/patterns/ProtractorToPlaywright.md
.grit/patterns/ReactToHooks.md
.grit/patterns/RemoveNodeBufferOffsetCheckFlag.md
.grit/patterns/common.grit
.grit/patterns/react.grit
.grit/patterns/split_trpc_router.md

update pattern definitions to conform to the form:
```
pattern foo (args...) {
<body>
}
```

chore: pattern definitions

---

.grit/patterns/add_type_caught_errors.md

Also adds a test for the negative side.

migrate `add_type_caught_errors`

---

.grit/patterns/split_trpc_router.md

Looks like `--update` misses some new lines.

fix: formatting for expected output files

---

.grit/patterns/split_trpc_router.md

Revert "update split_trpc"

---

.grit/patterns/EnzymeToRTL.md
.grit/patterns/no_eq_null.md
.grit/patterns/prefer_is_nan.md

fixes https://github.com/getgrit/rewriter/issues/5313
fixes https://github.com/getgrit/rewriter/issues/5306

fix: migrate `no_eq_null` and `prefer_is_nan`

---

.grit/patterns/no_dead_code.md

Closes https://github.com/getgrit/rewriter/issues/3717

feat: migrate `no_dead_code`

---

.grit/patterns/jest_array_containing.md

Closes https://github.com/getgrit/rewriter/issues/3714

feat: migrate `jest_array_containing`

---

.grit/patterns/marzano.grit
.grit/patterns/no_yoda_conditions.md

fixes https://github.com/getgrit/rewriter/issues/5312

chore: migrate `no_yoda_conditions`

---

.grit/patterns/es6_imports_to_require.md

needs to be merged simultaneously with https://github.com/getgrit/rewriter/pull/5609

chore: update es6-imports

---

.grit/patterns/importing.md
.grit/patterns/imports.grit
.grit/patterns/knockout_to_react.md
.grit/patterns/protractor_to_playwright.md

Also pulled out an "importing" markdown so we can have some nice tests.

feat: add a remove_import pattern

---

.grit/patterns/fix_jsx_file_extension.md

Resolves https://github.com/getgrit/rewriter/issues/5731

fix: fix_jsx_file_extension

---

.grit/patterns/react_to_hooks.md

Add some typings and use `current` properly

fix: better refs

---

.grit/patterns/react_to_hooks.md

Implements some basics to allow branching hook logic. Will follow up with another PR.

feat: implement alternative React hooks

---

.grit/patterns/openai_v4.md

This is just a PoC for now, need to do more.

feat: implement a basic OpenAI v4 migration

---

.grit/patterns/convert_negative_zero_equality_check_to_object_is.md

fix: remove annotation

---

.github/workflows/main.yaml
.grit/.gitignore

We really only need to test Mac + Linux.

chore: simplify runners

---

.grit/patterns/openai_v4.md

fix: valid js samples

---

.github/workflows/main.yaml
.grit/patterns/react_hooks.grit
.grit/patterns/react_to_hooks.md

fix: react default exports

---

.grit/patterns/protractor_to_playwright.md

fixes https://github.com/getgrit/rewriter/issues/6582
Probably not ideal, but I mean...

fix: protractor to playwright rewriting unrelated files

---

.grit/patterns/openai_v4.md

Fixes https://github.com/getgrit/js/issues/169

fix(openAI): inline config

---

.grit/patterns/openai_v4.md

fix: avoid suppressing v4 openai imports

---

.grit/patterns/openai_v4.md

Handles https://github.com/openai/openai-node/pull/266

chore: handle OpenAI renames

---

.grit/patterns/add_type_caught_errors.md
.grit/patterns/chai_to_jest.md
.grit/patterns/convert_negative_zero_equality_check_to_object_is.md
.grit/patterns/es6_exports.md
.grit/patterns/explicit_type_conversion.md
.grit/patterns/fix_jsx_file_extension.md
.grit/patterns/importing.md
.grit/patterns/inner_html_to_inner_text.md
.grit/patterns/jest_array_containing.md
.grit/patterns/no_console_log.md
.grit/patterns/no_iterator.md
.grit/patterns/prefer_early_return.md
.grit/patterns/react_to_hooks.md
.grit/patterns/react_to_hooks_mobx.md
.grit/patterns/remove_escape_markup.md
.grit/patterns/serverless_to_spin.md
.grit/patterns/split_trpc_router.md

For https://github.com/getgrit/rewriter/issues/6853

chore: ensure descriptive titles for all samples

---

.grit/patterns/react_hooks.grit
.grit/patterns/split_trpc_router.md

codependant on https://github.com/getgrit/rewriter/pull/6861

chore: curly-to-bracket

---

.grit/patterns/mux_v8.md

Closes #184.
Converts most of the old mux api to the new mux api.
Only has 3 tests for now. Working on adding more.

feat: Added grit transformer to upgrade to mux v8

---

.grit/patterns/mux_v8.md

Fixes https://github.com/getgrit/js/issues/190

fix: repair webhook issue with Mux

---

.grit/patterns/mui4_to_mui5.md

renamed theme-palette-type for mui4 to mui5.

Rename theme.palette.type for mui4 to mui5

---

.grit/patterns/importing.md
.grit/patterns/imports.grit
.grit/patterns/openrouter.md
.grit/patterns/util_upsert.md

The new `+=` operator allows us to insert multiple items with more safety

Use `+=` operator to insert after existing nodes

---

.grit/patterns/mux_v8.md

CC https://github.com/getgrit/rewriter/issues/7476

fix: use correct sample headings

---

.grit/patterns/openai_v4.md

fixes https://github.com/getgrit/rewriter/issues/7543

fix: don't rewrite non-openai imports

---

.grit/patterns/jest_to_vitest.md
.grit/patterns/react_hooks.grit

update patterns to conform to new arrow-function syntax

fix: Arrow call signature

---

.grit/patterns/jest_array_containing.md
.grit/patterns/moment_to_datefns.md
.grit/patterns/remove_escape_markup.md

https://github.com/getgrit/rewriter/pull/7567

chore: update spacing

---

.grit/patterns/mui4_to_mui5.md

It passes when pointing the SDK tests at this branch

fix: get mui passing in javascript tests

---

.grit/patterns/todo.grit

uses the grit function definition functionality to define two new functions

feat: add lines and todo functions

---

.grit/patterns/react_hooks.grit
.grit/patterns/react_to_hooks.md

For https://github.com/getgrit/rewriter/issues/7726

fix: handle more react scenarios

---

.grit/patterns/react_hooks.grit
.grit/patterns/react_to_hooks.md

For https://github.com/getgrit/rewriter/issues/7726

fix: more react cases

---

.grit/patterns/react_hooks.grit
.grit/patterns/react_to_hooks.md

For https://github.com/getgrit/rewriter/issues/7726

fix: react default props

---

.grit/patterns/react_hooks.grit
.grit/patterns/react_to_hooks.md

For https://github.com/getgrit/rewriter/issues/7726

fix: react aliased default props

---

.grit/patterns/hathora_ts.md

We should generally favor short names for patterns.

fix: better naming / devex for Hathora SDK

---

.grit/patterns/todo.grit

For https://github.com/getgrit/rewriter/issues/7815

feat: log todo

---

.grit/patterns/codecept_to_playwright.md

Requires https://github.com/getgrit/rewriter/pull/7933 deploy

feat: transform codecept waiters

---

.github/workflows/main.yaml
.grit/patterns/ai.grit
.grit/patterns/ai_choose.md
.grit/patterns/ai_match.md
ops/set_access_token.sh

Introduces new AI utilities:
- `ai_ask` to ask an AI to classify between a few choices
-

feat: add AI utility patterns

---

.grit/patterns/blocks.md
.grit/patterns/no_commented_out_code.md

It doesn't quite work perfectly yet, but is a good example of AI linting to start.

feat: add pattern for removing commented out code

---

.grit/patterns/codecept_to_playwright.md

Needs simultaneous merge with https://github.com/getgrit/rewriter/pull/8004

fix: remove comma workaround
