getgrit/js

.grit/grit.yaml, .grit/patterns/NoConsoleLog.md
Now that pattern resolution between multiple file types is fixed, re-instate `NoConsoleLog`.
=> Revert back

.grit/patterns/FlowToTypeScript.md
It's probably a safer bet to assume all Flow files contain at least one type annotation, but we ideally should match if *either* condition is true without short-circuiting.
=> fix: transform Flow files with no imports

.grit/patterns/ES6Imports.md
Previously we didn't handle raw `require` imports.
=> fix(ES6Imports): handle default imports as * imports

.grit/patterns/NoArrayConstructor.md, .grit/patterns/NoDeadCode.md, .grit/patterns/NoSparseArraysRemoveExtraCommas.md, .grit/patterns/NoSparseArraysToUndefined.md, .grit/patterns/NoThrowLiteral.md, .grit/patterns/NoYodaConditions.md, .grit/patterns/ProtractorToPlaywright.md, .grit/patterns/ReactToHooks.md, .grit/patterns/common.grit, .grit/patterns/react.grit
were updating the grammar so that a variable must be prepended with a `$`
=> fix: require dollar sign

.grit/patterns/FixJSXFiles.md
Clean up extensions so the TypeScript compiler stops complaining. Fixes https://github.com/getgrit/rewriter/issues/2915.
=> feat: add FixJSXFiles pattern

.grit/patterns/ES6Imports.md
This seems pretty straightforward and common enough that it's worth catching.
=> fix: handle dotenv in ES6Imports

.grit/patterns/ES6Exports.md, .grit/patterns/ES6Imports.md
Resolves https://github.com/getgrit/rewriter/issues/3903
Studio: https://app.grit.io/studio?key=Jj-uMNIKi-lQBbmn5I6bH
This can handle the basic case, but cannot handle this:
```
const { sub1, sub2 } = require("mod5"); // not handled
module.exports = {
sub1,
sub2
};
```
It's just difficult to handle matching a sublist of the module.exports
```
// TODO difficult to handle matching a sublist of the module.exports
// `const { $imports } = require($val)` => `export { $transformed } from "$val"` where {
//     $imports <: some bubble($transformed, $name) {ObjectProperty(key=$subkey, value=$subval) where {
//         $subval <: $name
//         $transformed = [...$transformed, `$subkey as $subval`]
//     } }
// }
```
=> feat: ES6Exports handles export of a require

.grit/patterns/common.grit
Useful for renamed packages, etc.
=> feat: add a MoveImport pattern

.grit/patterns/common.grit
- Adds `ensureNamespaceImportFrom`, which also avoids existing imports. 
- Adds an `isNamespaceImported` predicate.
- Adjusts `AddNamespaceImportFrom` to make it idempotent.
=> add `ensureNamespaceImportFrom`

.grit/patterns/split_trpc_router.md
`grit patterns test` does not pass, and it did not in the previous version either -- I guess because it would require multi-output support.
=> migrate: `split_trpc_router`

.github/workflows/main.yaml
GitHub Actions has been rather flaky recently and [Namespace](https://namespace.so/) looks like a good alternative to try for both CI and, eventually, VM execution. Adding it as an option in the matrix for evaluation.
=> chore: try switching to namespace cloud runners

.grit/patterns/split_trpc_router.md
update required for https://github.com/getgrit/rewriter/pull/5084, without that pr this will break the pattern.
=> chore: match routes_object against a list

.grit/patterns/no_async_promise_executor.md
fixes https://github.com/getgrit/rewriter/issues/5299
=> chore: migrate `no_async_promise_executor`

.grit/patterns/openai_v4.md
For https://github.com/getgrit/rewriter/issues/5902
With slight modifications - the transcription example does not have `import OpenAI from 'openai'` additionally prepended, and the final error handling case doesn't rename the constant or change `console.log` to `console.error`.
=> feat: openai covering migration sample cases

.grit/patterns/openai_v4.md
Including the early includes check is a massive performance boost:
```
time gritdev apply openai_v4 packages/universal
Processed 32 files and found 0 matches
/Users/morgante/code/grit/rewriter/target/release/marzano apply openai_v4   0.80s user 0.05s system 84% cpu 0.999 total
~/code/grit/rewriter   main  time gritdev apply openai_v4 packages/universal
Processed 32 files and found 0 matches
/Users/morgante/code/grit/rewriter/target/release/marzano apply openai_v4   16.35s user 0.21s system 97% cpu 16.902 total
```
=> fix: use any instead of maybe

.grit/patterns/literal.md, .grit/patterns/no_yoda_conditions.md
This is mostly for ease of referencing / documentation.
=> chore: extract the "literal" pattern into a separate doc

.grit/patterns/react_hooks.grit, .grit/patterns/react_to_hooks.md, .grit/patterns/react_to_hooks_mobx.md
Default exports are blocked by https://github.com/getgrit/rewriter/issues/6514.
for #162
=> fix: react exports

.grit/patterns/react_hooks.grit
`tree-sitter parse` returns no missing nodes (there was a missing node before).
=> fix: react to hooks rewrite accesses

.grit/patterns/importing.md, .grit/patterns/imports.grit
Imports location is put in the following priority:
- Below the shebang
- At the top of the file
Fixes #188
=> fix: insert imports after shebang

.grit/patterns/no_console_log.md
Now that we clean up empty statements automatically, this can be simplified.
=> feat: simplify no console log

.grit/patterns/importing.md, .grit/patterns/imports.grit
Currently, if you use `remove_import(moduleToRemove)` on this line of Javascript:
```javascript
import myDefaultExport, { moduleToRemove } from "pkg";
```
Grit will delete the whole line instead of returning
```javascript
import myDefaultExport from "pkg";
```
This PR attempts to fix the bug such that only the named import list gets removed. The existing path in `remove_import` is:
```
// Handle named import
import_clause(name = named_imports($imports)) where {
$others = `false`,
if ($imports <: [$name]) {
$import => .
} else { ... }
}
```
The idea of this PR is to change the case where `imports` is a list with just the module to remove from removing the whole line.
Instead, we check if we have a non-empty default export with `default=$default_export` + `!$default_export <: .`, and if so, …
=> fix: `remove_import(mymodule)` pattern to not delete the whole line when given `import defaultExport, {myModule}`

.grit/patterns/importing.md, .grit/patterns/imports.grit
required for yaml equivalence classes
=> chore: snippets aren't strings

.grit/patterns/react_hooks.grit, .grit/patterns/react_to_hooks.md
=> fix: hook import
